#include "Building.h"

/**
 * @brief Constructor for the Building class.
 * @param buildingName The name of the building.
 * @param buildingCost The cost of the building.
 * @param buildingIncome The income generated by the building.
 */
Building::Building(string buildingName, int buildingCost, int buildingIncome)
    : name(buildingName), cost(buildingCost), income(buildingIncome)
{
    cout << "Building object is being created" << endl;
}

/**
 * @brief Destructor for the Building class.
 */
Building::~Building()
{
    cout << "Building object is being deleted" << endl;
}

/**
 * @brief Get the name of the building.
 * @return The name of the building.
 */
string Building::getName() const
{
    return name;
}

/**
 * @brief Get the cost of the building.
 * @return The cost of the building.
 */
int Building::getCost() const
{
    return cost;
}

/**
 * @brief Get the income generated by the building.
 * @return The income generated by the building.
 */
int Building::getIncome() const
{
    return income;
}

/**
 * @brief Set the name of the building.
 * @param buildingName The name of the building.
 */
void Building::setName(string buildingName)
{
    name = buildingName;
}

/**
 * @brief Set the cost of the building.
 * @param buildingCost The cost of the building.
 */
void Building::setCost(int buildingCost)
{
    cost = buildingCost;
}

/**
 * @brief Set the income generated by the building.
 * @param buildingIncome The income generated by the building.
 */
void Building::setIncome(int buildingIncome)
{
    income = buildingIncome;
}

/**
 * @brief Display information about the building.
 */
void Building::displayInfo() const
{
    cout << "Building Name: " << name << endl;
    cout << "Building Cost: " << cost << endl;
    cout << "Building Income: " << income << endl;
}

/**
 * @brief Display detailed information about the building.
 */
void Building::displayBuildingInfo() const
{
    displayInfo();
}

