#include <iostream>
#include "Farm.h"
#include "Building.h"

using namespace std;

/**
 * @brief Constructor for the Farm class.
 * @param buildingName The name of the building.
 * @param buildingCost The cost of the building.
 * @param buildingIncome The income generated by the building.
 * @param buildingFoodProduction The food production of the farm.
 */
Farm::Farm(string buildingName, int buildingCost, int buildingIncome, int buildingFoodProduction)
    : Building(buildingName, buildingCost, buildingIncome), foodProduction(buildingFoodProduction), lvl(1) {}

/**
 * @brief Destructor for the Farm class.
 */
Farm::~Farm() {}

/**
 * @brief Display detailed information about the building.
 */
void Farm::displayBuildingInfo() const
{
    Building::displayBuildingInfo();
    cout << "Food production: " << foodProduction << endl;
    cout << "Level: " << lvl << endl;
}

/**
 * @brief Upgrade the farm.
 */
void Farm::upgrade()
{
    cost *= 2;
    income *= 2;
    foodProduction *= 2;
    lvl++;
    cout << "Farm has been upgraded to level " << lvl << endl;
}

/**
 * @brief Harvest the food produced by the farm.
 */
void Farm::harvest()
{
    cout << "Harvesting " << foodProduction << " food..." << endl;
    cout << "Food has been added to the city's resources." << endl;
}