#pragma once

#include <iostream>
#include <string>

class Building
{
    protected:
        // Attributes
        std::string name; // Name of the building
        int cost; // Cost of the building
        int income; // Income generated by the building

    public:
        // Methods
        Building(std::string buildingName, int buildingCost, int buildingIncome); // Constructor
        virtual ~Building(); // Destructor

        virtual void displayBuildingInfo() const; // Display building information
};