#pragma once

#include <iostream>
#include <string>
#include <vector>

using namespace std;

/**
 * @class Building
 * @brief A class representing a building with a name, cost, and income.
 * 
 * The Building class provides attributes to store the name, cost, and income
 * of a building. It serves as a base class for more specific types of buildings.
 */
class Building
{
    protected:
        string name; ///< Name of the building
        int cost; ///< Cost of the building
        int income; ///< Income generated by the building

    public:
        /**
         * @brief Constructor for the Building class.
         * @param buildingName The name of the building.
         * @param buildingCost The cost of the building.
         * @param buildingIncome The income generated by the building.
         */
        Building(string buildingName, int buildingCost, int buildingIncome);

        /**
         * @brief Destructor for the Building class.
         */
        virtual ~Building();

        /**
         * @brief Get the name of the building.
         * @return The name of the building.
         */
        string getName() const;

        /**
         * @brief Get the cost of the building.
         * @return The cost of the building.
         */
        int getCost() const;

        /**
         * @brief Get the income generated by the building.
         * @return The income generated by the building.
         */
        int getIncome() const;

        /**
         * @brief Set the name of the building.
         * @param buildingName The name of the building.
         */
        void setName(string buildingName);

        /**
         * @brief Set the cost of the building.
         * @param buildingCost The cost of the building.
         */
        void setCost(int buildingCost);

        /**
         * @brief Set the income generated by the building.
         * @param buildingIncome The income generated by the building.
         */
        void setIncome(int buildingIncome);

        /**
         * @brief Display information about the building.
         */
        virtual void displayInfo() const;

        /**
         * @brief Display detailed information about the building.
         */
        virtual void displayBuildingInfo() const;
};