#pragma once

#include "Building.h"

/**
 * @class Farm
 * @brief A class representing a farm building.
 * 
 * The Farm class inherits from the Building class and adds attributes and methods
 * specific to a farm, such as food production and level.
 */
class Farm : public Building
{
    private:
        // Attributes
        int foodProduction; ///< Food production of the farm
        int lvl; ///< Level of the farm

    public:
        // Methods

        /**
         * @brief Constructor for the Farm class.
         * @param buildingName The name of the building.
         * @param buildingCost The cost of the building.
         * @param buildingIncome The income generated by the building.
         * @param buildingFoodProduction The food production of the farm.
         */
        Farm(std::string buildingName, int buildingCost, int buildingIncome, int buildingFoodProduction);

        /**
         * @brief Destructor for the Farm class.
         */
        ~Farm();

        /**
         * @brief Display information about the building.
         */
        void displayBuildingInfo() const override;

        /**
         * @brief Upgrade the farm.
         */
        void upgrade();

        /**
         * @brief Harvest the food produced by the farm.
         */
        void harvest();
};